### ISSUE TITLE
BufferMap

### ISSUE THREAD

**Issue by nodech** [bcoin-org/bdb#3]
I was experimenting with `buffer` maps as well, I also looked into `bdb` to get `BufferMap` not convert buffers at all (Similar to `std::map`) because of the js memory overhead when working with strings (fortunately I don't need huge keys), I ran several benchmarks today after seeing
bcoin-org/bcoin/issues/533

Is there any reason to use `rbt` for `memdb` ? 

@chjj

**Comment by chjj** [comment]
`rbt` is used because we need sorted keys in order to emulate leveldb iterators.

**Comment by nodech** [comment]
Thanks. Forgot about sorting, wanted buffers as keys so much. :)
